# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - r: devel
    - r: release
      # Code coverage for R: see example at https://github.com/codecov/example-r
      after_success:
        - Rscript -e 'library("covr"); codecov()'
    - r: oldrel
  allow_failures:
    - r: devel
    - r: oldrel